### ISSUE TITLE
Known Issues Affecting SDK

### ISSUE THREAD

**Issue by GregChan** [smartcar/java-sdk#31]
There are some known issues with this SDK, which we're working on fixing. These include:
- ~~lock - is form url encoding the body instead of sending it as json (#29)~~
- ~~unlock - is form url encoding the body instead of sending it as json (#29)~~
- ~~odometer - has the wrong data type, should be `double` instead of `int` (#29)~~
- exchangeRefreshToken - not verified

**Comment by gurpreetatwal** [comment]
Verified the `exchangeRefreshToken` method
